version: '3.9'

volumes:
  pg-data:

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - ./backend/CRUD/stocks_products/.env
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  api:
    build: ./backend
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi" 
    depends_on:
      - db
    env_file:
      - ./backend/CRUD/stocks_products/.env
    ports:
      - "81:8000"
    volumes:
      -  ./backend/CRUD/static:/static

  nginx:
    build: nginx
    depends_on:
      - api
    volumes:
      - ./backend/CRUD/static:/static:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro 
    ports:
      - "80:8000"
