version: '3.8'

volumes:
  pg-data:

services:
  web:
    build: ./backend
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi" 
    depends_on:
      - db
    env_file:
      - ./backend/CRUD/stocks_products/.env

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  
    
  # nginx:
  #   build: nginx
  #   ports:
  #     - "5432:80"
  #   depends_on:
  #     - api
  #   networks:
  #     - backend