version: '3.9'

volumes:
  pg-data:

services:
  db:
    image: postgres:15.0-alpine
    env_file:
      - ./backend/CRUD/stocks_products/.env
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  api:
    build: ./backend
    command: bash -c "python manage.py migrate && 
             gunicorn -b 0.0.0.0:8000 stocks_products.wsgi" 
    env_file:
      - ./backend/CRUD/stocks_products/.env
    ports:
      - "8000:8000"
    volumes:
      -  ./backend/CRUD/static:/static
    depends_on:
      - db
    
  nginx:
    build: nginx
    volumes:
      - ./backend/CRUD/static:/static:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
